### ISSUE TITLE
Retro timer like mobster's break timer (http://mobster.cc/) 

### ISSUE THREAD

**Issue by Austin117** [mobtimeapp/mobtime#120]
Check out Mobster's break timer here: http://mobster.cc/
I think it would be super cool if there was a retro timer that had the same exact settings as this break timer but would prompt the team to do a mini retro. 
Bonus: suggest random retro formats, questions, or prompts (e.g. turn up the good, start/stop/more/less, etc.)

**Comment by mrozbarry** [comment]
Although I added a more generic issue for multiple timers, I think we need to flush out this timer feature here. A part of me just wants to push users onto https://retrotool.io/ , which does provide a timer and format options.

I'd also want to know how many teams need a timer specifically for reflection/retro that use mobtime.

**Comment by Austin117** [comment]
Right on!
Up to chat anytime on why this was requested to be integrated. I think it
works be excellent but understand that work can be a lot.

**Comment by tedyoung** [comment]
I'd like to see a retro option after a full cycle (or 2 cycles, etc.) through the mob. Right now I have to remember who started the cycle. It doesn't have to be anything sophisticated, simply a pop up or note saying "Mini-Retro Time". I wouldn't want the retro itself integrated.

**Comment by tedyoung** [comment]
btw, something like https://github.com/mobtimeapp/mobtime/issues/119 would also serve this purpose for us. We'd do a mini-retro (and take a break) during the break time.

**Comment by mrozbarry** [comment]
A thing I keep thinking about is what is the mobtime app actually responsible for? What is the smallest and simplest tool that could enable collaborative mobbing.

For instance, this issue started as essentially "can you make this more like mobster" but that makes me wonder what value there is of having a second "mobster" app?

Then there's a thing where teams that mob are fairly unique. For instance, my team at work decides when we need breaks just based on mental fatigue or time, and have never had a problem, _but_ it's clear that other teams don't function that way and need a second timer.

That being said, I am in the midst of planning mobtime bot extensions, where people could write mini applications that connect to their timer to manage features. For instance, a retro bot that tracks rotations and sends out a notification when n cycles have happened.

But in terms of the core of mobtime, my absolute preference is to keep it as simple as possible. One time, one team, and basic mob management. Even goals is probably a little more than what mobtime should actually be responsible for - most teams use other project/task tracking via github/trello/jira/etc.

So on that note, I'm going to close this issue, but I'm still open to discussing this further. I don't want to alienate any users of mobtime, and people that want to see it expand and grow, so take my statements with love and not anger <3
