### ISSUE TITLE
Can I make it really narrow in the browser?

### ISSUE THREAD

**Issue by BigTom** [mobtimeapp/mobtime#172]
I would like to make the browser view really narrow so I can use less screen estate.

enhancement request

**Comment by mrozbarry** [comment]
Define narrow - what's your screen resolution, and how many pixels wide. Also, have you considered using your phone as a dedicated timer screen?

**Comment by mrozbarry** [comment]
Just want to ping this issue one more time, can you clarify the pixel width you're interested in? If you're not sure, or don't need this issue any more, I'll close it in a few days. Thanks
