### ISSUE TITLE
Add participant field auto-suggests payment information

### ISSUE THREAD

**Issue by dbartholomae** [mobtimeapp/mobtime#179]
We just ran into a situation where our browser tried to add payment information when adding a participant.
I think this could be solved by adding `autocomplete="off"` to the Add participant input field.

**Comment by mrozbarry** [comment]
Funny, a co-worker just ran into that a week or two ago, I asked him to make a ticket so I wouldn't lose track, and I guess he lost track, then I did. Thanks for the report, I'll get this fixed soon!
