### ISSUE TITLE
Reverse Mob Display Order?

### ISSUE THREAD

**Issue by tedyoung** [mobtimeapp/mobtime#201]
Maybe this is already supported, but what I want is where the Driver becomes the Navigator, which is what the Mob Order of "Navigator,Driver" does, but I want the Driver displayed at the top. In our remote mob, the new Driver is the one who has to take over the screen sharing, and we've been struggling with seeing who the new Driver is since they're not displayed at the top.

**Comment by mrozbarry** [comment]
Some people use `Navigator,Driver,Next`. Does that work for your team or is there a further issue that I'm not aware of?

**Comment by dpolivaev** [comment]
You already can change the order in the timer settings tab

**Comment by mrozbarry** [comment]
I'm going to close this, but @tedyoung if I missed something, please let me know, and I'll re-open this. Thanks!
