### ISSUE TITLE
Allow to specify a replacement for default mob member role name currently called "Mob"

### ISSUE THREAD

**Issue by dpolivaev** [mobtimeapp/mobtime#207]
Because the term "mob programming" is getting replaced by "ensemble programming" to avoid bad feelings and be more inclusive, it would be nice, if we could specify a name for the default mob member role in the timer settings.

Currently, only specific roles like "driver" or "navigator" are configurable, which is great, but the default is not configurable and hardcoded to be "mob".

**Comment by mrozbarry** [comment]
I'm going to close this, but if there is any more relevant feedback, please feel free to re-open or start a new issue.
