### ISSUE TITLE
Rotating mob members results in console error after latest update

### ISSUE THREAD

**Issue by theparticleman** [mobtimeapp/mobtime#215]
After the latest update (Jan 2022), rotating through mob members results in a console error.

![image](https://user-images.githubusercontent.com/4561333/147985616-e03fa6c7-70b5-4910-aea9-4493df39eb4b.png)

Interestingly, my team members and I got this same error in Chromium Edge, Brave, and Chrome on Windows. Other team members using MacOS with Brave and Chrome did not get the console error when rotating through mob members. I'm not sure if the OS difference is actually important or just coincidental.

**Comment by mrozbarry** [comment]
Oh, sorry about that, I will fix and deploy that in the next couple of minutes!

**Comment by mrozbarry** [comment]
@theparticleman give your timer a refresh, everything should be working as expected

**Comment by theparticleman** [comment]
Thanks so much! The console error appears to be resolved.

One of my teammates started looking into the issue to see if he could submit a PR, but you fixed it before he finished looking into it.
