### ISSUE TITLE
Fix reorder icon 

### ISSUE THREAD

**Issue by tbauman88** [mobtimeapp/mobtime#217]
## Problem
The reorder icon is no longer working, had to manually pop open the more menu and use the up/down reorder icons

![Screen Shot 2022-01-04 at 9 56 12 AM](https://user-images.githubusercontent.com/25010884/148077908-2a2627d2-357e-4e3c-acc9-7b1e55b322af.png)

**Comment by ssshake** [comment]
This issue also occurs for reordering goals #234
