### ISSUE TITLE
Enable Timer Sounds setting does not persist on refresh

### ISSUE THREAD

**Issue by NByam13** [mobtimeapp/mobtime#224]
When you set the timer sounds to enabled and perform a refresh, the timer sounds are returned to their default of off.

**Comment by mrozbarry** [comment]
Correct. The way audio in the browser works requires page interaction before any audio can automatically play, so this is a feature, in a sense. Maybe there is a better way to mitigate this, though.

**Comment by NByam13** [comment]
yeah ok that's fair, I'll close this one then

**Comment by mrozbarry** [comment]
Hah, actually, I'm going to re-open this. I think what I'll do is...

 1. Save the user choice to local storage
 2. On timer load, if that was saved previously, show a toast message `"Click here to activate sounds [it's sound time!] [not this time] [never again]"` or something like that
 3. If the user clicks the positive button, check the box, and you're good to go
 4. If the user clicks the negative button, don't change the local storage data, but don't do sounds this time
 5. If the user clicks the never button, change the data in local storage, and don't use sounds
