### ISSUE TITLE
Mobtime changed from blue to white and buttons changed to link

### ISSUE THREAD

**Issue by ethanstrominger** [mobtimeapp/mobtime#230]
Mobtime used to be blue, now it is white.  Is that intentional?  Also, buttons have changed to just be plain text.  Clicking on them still works, but they do not look like buttons.

**Comment by mrozbarry** [comment]
Is this when running locally, and either way, can you provide a screenshot?

**Comment by ethanstrominger** [comment]
This is when I run from web mobti.me

[image: image.png]

**Comment by mrozbarry** [comment]
Hmm, can't see the image. I'd try just clearing your cache and give it another shot.

**Comment by ethanstrominger** [comment]
This link should work: https://drive.google.com/file/d/1FJVNq4FD1MyVFLF4tffNWKVsANw4CVEG/view?usp=sharing

I cleared the cache and tried it from my mobile device, same result.

**Comment by mrozbarry** [comment]
Oh, that was intentional but I can make them look more like buttons.

**Comment by tedyoung** [comment]
I'd also like those to be more obviously buttons.

(And I'm sure you got a lot of this type of feedback, but I preferred the less-bright blue theme -- note I am explicitly _not_ asking for a dark theme.)
