### ISSUE TITLE
UI: Need highlighting for Navigator/Driver

### ISSUE THREAD

**Issue by tedyoung** [mobtimeapp/mobtime#233]
![image](https://user-images.githubusercontent.com/382660/149572169-4189adf8-696a-43b4-87ce-65eef1f8d298.png)

With the current styling, it's very difficult to see who the current navigator/driver are. The bolding of their names isn't enough. Could we get a different background coloring for those rows?

(We don't use the Overview as we want to see who's coming up after the current driver.)

**Comment by mrozbarry** [comment]
Sure, I can do that, but if you did want to use the overview, you could set your roles to `Navigator,Driver,Next`, too.
