### ISSUE TITLE
Persist people and team settings permanently

### ISSUE THREAD

**Issue by dschinkel** [mobtimeapp/mobtime#247]
It's a huge pain to have to re-enter the same folks in a mobbing session.  Having to add the same settings in the settings and other tabs.

Right now it persists for only 3 days.  I don't understand the arbitrary number here and think it would be more work to actually have limited something like this, than just let it persist in the first place.

I don't see any reason not to persist this.  We're talking about people's names and mob team's preferences to finally stick and stay.  If we want to add or remove a person from the mob, it's a simple action.  

There is no confidential information here to worry about, it's just names and settings.

But having to add everyone back into the mob makes the mobbing experience painful

**Comment by mrozbarry** [comment]
Just to clarify, the data persists for _at least_ 3 days. Every update to the timer resets the expiry to 3 days from that time, so theoretically, the timer would last indefinitely until the timer hasn't been accessed or updated for 3 days.

**Comment by mrozbarry** [comment]
@dschinkel does that make sense? I think I misunderstood your concern from our previous conversation, but I'm hoping this clears up what the 3-days means, and that it's not a strict total of 3 days, but more of a rolling window.

**Comment by dschinkel** [comment]
I think this will be ok, thanks
