### ISSUE TITLE
Add option in settings to automatically start timer after it beeps

### ISSUE THREAD

**Issue by ToiWright** [mobtimeapp/mobtime#269]
We often start the time when a new person becomes the driver. We think this would be a very helpful option for many people.

**Comment by mrozbarry** [comment]
My _initial_ inclination is that this is likely not how most teams mob (but I am open to being wrong), but that said, I am more than open to getting a PR, and worst case, I don't merge it BUT you and your team have a fork with the feature you want, which doesn't seem that bad.

**Comment by ToiWright** [comment]
Hello Alex,

 

Thanks for getting back to us. We love your mob timer. When it goes off, we rotate the positions, but we always forget to restart it. I don’t know why. 

 

I will share your response with the team.

 

Regards,

Toi Wright

**Comment by mrozbarry** [comment]
As a possible solution, did you know you can load up the timer on your smart phones as an extra screen? The "Share" tab has a QR code that you can scan using your camera app (or whatever you want to use to scan QR codes), and it can make it easy to see if the timer was missed. Also, depending on the size of your mob, multiple people can (and maybe should?) have the timer open, so there are more chances that you don't forget to start your timer.

**Comment by ToiWright** [comment]
Thanks for the suggestions. I will share them with the team.

**Comment by mrozbarry** [comment]
I'm going to close this issue, but if you and your team really wants to see this feature and possibly PR something, feel free to re-open.
